print("Original:\n")
###################
print("                 /\\")
print("                /  \\")
print("               /    \\")
print("              /      \\")
print("     /\\      /        \\      /\\")
print("    /  \\    /          \\    /  \\")
print("   /    \\  /            \\  /    \\")
print("  /      \\/              \\/      \\")
print(" /                                  \\")
print(" \\                                  /")
print("  \\      /\\              /\\      /")
print("   \\    /  \\            /  \\    /")
print("    \\  /    \\          /    \\  /")
print("     \\/      \\        /      \\/")
print("              \\      /")
print("               \\    /")
print("                \\  /")
print("                 \\/")
###################
print("\nCon pocos Print:\n")
###################
print("                 /\\\n                /  \\\n               /    \\\n              /      \\\n     /\\      /        \\      /\\\n    /  \\    /          \\    /  \\\n   /    \\  /            \\  /    \\\n  /      \\/              \\/      \\\n /                                  \\\n \\                                  /\n  \\      /\\              /\\      /\n   \\    /  \\            /  \\    /\n    \\  /    \\          /    \\  /\n     \\/      \\        /      \\/\n              \\      /\n               \\    /\n                \\  /\n                 \\/")###################
###################
print("\nMas grande:\n")
###################
print("                                  /\\")
print("                                 /  \\")
print("                                /    \\")
print("                               /      \\")
print("                              /        \\")
print("                             /          \\")
print("                            /            \\")
print("                           /              \\")
print("         /\\              /                \\              /\\")
print("        /  \\            /                  \\            /  \\")
print("       /    \\          /                    \\          /    \\")
print("      /      \\        /                      \\        /      \\")
print("     /        \\      /                        \\      /        \\")
print("    /          \\    /                          \\    /          \\")
print("   /            \\  /                            \\  /            \\")
print("  /              \\/                              \\/              \\")
print(" /                                                                  \\")
print("/                                                                    \\")
print("\\                                                                    /")
print(" \\                                                                  /")
print("  \\              /\\                              /\\              /")
print("   \\            /  \\                            /  \\            /")
print("    \\          /    \\                          /    \\          /")
print("     \\        /      \\                        /      \\        /")
print("      \\      /        \\                      /        \\      /")
print("       \\    /          \\                    /          \\    /")
print("        \\  /            \\                  /            \\  /")
print("         \\/              \\                /              \\/")
print("                           \\              /")
print("                            \\            /")
print("                             \\          /")
print("                              \\        /")
print("                               \\      /")
print("                                \\    /")
print("                                 \\  /")
print("                                  \\/")
##################
print("\nDuplicado:\n")
###################
print("                 /\\                     "*2)
print("                /  \\                    "*2)
print("               /    \\                   "*2)
print("              /      \\                  "*2)
print("     /\\      /        \\      /\\       "*2)
print("    /  \\    /          \\    /  \\      "*2)
print("   /    \\  /            \\  /    \\     "*2)
print("  /      \\/              \\/      \\    "*2)
print(" /                                  \\   "*2)
print(" \\                                  /   "*2)
print("  \\      /\\              /\\      /    "*2)
print("   \\    /  \\            /  \\    /     "*2)
print("    \\  /    \\          /    \\  /      "*2)
print("     \\/      \\        /      \\/       "*2)
print("              \\      /                  "*2)
print("               \\    /                   "*2)
print("                \\  /                    "*2)
print("                 \\/                     "*2)