# Abraham M.R. 23310382
print("Bienvenido a la calculadora simple de Python")
X = float(input("Ingresa tu primer valor: "))
Y = float(input("Ingresa tu segundo valor: "))
print("Al Sumarlos da:", X + Y)
print("Restarlos es:", X - Y)
print("Multiplicarlos entre si da:", X * Y)
print("Por ultimo, el Dividirlos da:", X / Y)
print("¡Eso es todo, amigos!")
print("\n╔══════════════════════════════════════════════╗")
print(" RECUERDEN: SI SU CALCULADORA NO FUNCIONA")
print("╚══════════════════════════════════════════════╝")
print("\n╔════════════════════════════════════════════════════════════╗")
print(" PROBABLEMENTE SOLO OLVIDARON CONVERTIR \n EL input() A int()… Y TODO ERAN VARIOS input() Y UN print()\n\n Hasta la proxima amigos, Darkdemon19 les desea buen dia!")
print("╚════════════════════════════════════════════════════════════╝")